import type { Metadata } from "next";
import Link from "next/link";
import { ArrowRight, BadgeCheck, Check, CircleDollarSign, GitBranch, Network, ShieldCheck, Sparkles, TimerReset, Users } from "lucide-react";
import { launchPlans, launchPricingNote } from "@/lib/plans";

export const metadata: Metadata = {
  title: { absolute: "Feelow AI | Customer-reported problems to verified fixes" },
  description: "Resolve revenue-impacting customer defects with clustered support evidence, engineering context, human approval, release verification, and customer follow-up.",
  robots: { index: true, follow: true },
  openGraph: {
    title: "Feelow AI | Customer-reported problems to verified fixes",
    description: "Turn repeated support reports into one engineering-ready problem, a verified release, and completed customer follow-up.",
    siteName: "Feelow AI",
    type: "website",
  },
  twitter: {
    card: "summary_large_image",
    title: "Feelow AI | Customer-reported problems to verified fixes",
    description: "Turn repeated support reports into one engineering-ready problem, a verified release, and completed customer follow-up.",
  },
};

const outcomes = [
  { icon: Network, title: "One problem, not 30 tickets", text: "Group differently worded support reports into a persistent defect with visible evidence and confidence." },
  { icon: CircleDollarSign, title: "Revenue impact, not vote count", text: "Prioritize using affected accounts, ARR, renewal risk, severity, SLA, frequency, and confidence." },
  { icon: GitBranch, title: "Engineering evidence, not a vague handoff", text: "Check existing work, then investigate likely owners, repositories, files, commits, and releases." },
  { icon: ShieldCheck, title: "Verified closure, not shipped and forgotten", text: "Approve external actions, verify the release outcome, and follow up with every affected customer." },
];

const workflow = ["Collect signals", "Normalize & redact", "Cluster problems", "Score impact", "Investigate code", "Approve action", "Track release", "Verify outcome"];

export default function LandingPage() {
  return <div className="landing">
    <a className="skip-link" href="#landing-content">Skip to content</a>
    <header className="landing-nav"><Link className="landing-brand" href="/"><span className="brandmark" aria-hidden="true">F</span><strong>Feelow AI</strong></Link><nav aria-label="Landing navigation"><a href="#product">Product</a><a href="#fit">Who it is for</a><a href="#workflow">Workflow</a><a href="#pricing">Pricing</a><a href="#trust">Trust</a></nav><div className="landing-actions"><Link className="btn" href="/overview">View sandbox</Link><a className="btn primary" href="mailto:shanmukhsain@gmail.com?subject=Feedback-to-Fix%20Design%20Partner%20Pilot">Apply for pilot <ArrowRight aria-hidden="true" size={14}/></a></div></header>

    <main id="landing-content">
    <section className="landing-hero"><div className="hero-copy"><div className="hero-kicker"><Sparkles aria-hidden="true" size={14}/> Feedback-to-fix operations for B2B SaaS</div><h1>Resolve customer-reported defects before they become churn.</h1><p>Feelow AI turns repeated support reports into one revenue-ranked, engineering-ready problem—then governs the path through approval, release verification, and customer follow-up.</p><div className="hero-actions"><a className="btn primary large" href="mailto:shanmukhsain@gmail.com?subject=Feedback-to-Fix%20Design%20Partner%20Pilot">Run a feedback-to-fix audit <ArrowRight aria-hidden="true" size={16}/></a><Link className="btn large" href="/overview">Explore free sandbox</Link></div><div className="hero-proof"><span><Check aria-hidden="true" size={14}/> Works above your existing stack</span><span><Check aria-hidden="true" size={14}/> Human approval by default</span><span><Check aria-hidden="true" size={14}/> Free sandbox uses simulated data</span></div></div>

      <div className="hero-product" aria-hidden="true"><div className="preview-chrome"><div className="preview-dots"><span/><span/><span/></div><span>Product problem · FF-142</span><span className="preview-status">Needs review</span></div><div className="preview-body"><div className="preview-sidebar"><div className="preview-logo">F</div>{[1,2,3,4,5,6].map((item) => <i key={item}/>)}</div><div className="preview-content"><div className="preview-eyebrow">HIGH-IMPACT PROBLEM</div><h2>Large CSV exports produce empty files</h2><p>3 corroborating customer reports after release 4.18.2</p><div className="preview-metrics"><div><small>Affected revenue</small><strong>$394k ARR</strong></div><div><small>Accounts</small><strong>3 enterprise</strong></div><div><small>Confidence</small><strong>92%</strong></div></div><div className="preview-grid"><section><div className="preview-section-title">Supporting evidence</div>{["Intercom · Northstar Labs", "Zendesk · Acme Health", "Slack · Atlas Cloud"].map((item, index) => <div className="preview-evidence" key={item}><span>{96-index*4}%</span><div><strong>{item}</strong><i/></div></div>)}</section><section><div className="preview-section-title">Impact score</div><div className="preview-score">79</div><div className="preview-bars">{[88,85,76,72].map((value) => <i style={{width:`${value}%`}} key={value}/>)}</div><div className="preview-approval"><BadgeCheck size={15}/><span><strong>Approval required</strong><small>GitHub issue · Low risk</small></span></div></section></div></div></div></div>
    </section>

    <section className="landing-trustbar" aria-label="Connected systems"><span>Built to connect the tools your teams already use</span>{["Intercom", "Zendesk", "Slack", "GitHub", "Jira", "Linear", "Sentry", "PostHog"].map((item) => <strong key={item}>{item}</strong>)}</section>

    <section className="landing-section" id="product"><div className="section-intro"><span>Customer issue operations</span><h2>Own the expensive gap between support and engineering.</h2><p>Feedback collection and AI summaries are no longer enough. Feelow AI preserves the customer problem, business context, engineering evidence, human decision, and verified outcome as one durable record.</p></div><div className="outcome-grid">{outcomes.map(({icon:Icon,title,text}) => <article key={title}><div className="outcome-icon"><Icon aria-hidden="true" size={19}/></div><h3>{title}</h3><p>{text}</p></article>)}</div></section>

    <section className="fit-section" id="fit"><div className="fit-copy"><span className="section-label">Focused initial market</span><h2>Built for B2B SaaS teams where one recurring defect can threaten a renewal.</h2><p>The first product is intentionally narrow. It solves the repeated, cross-functional work of recognizing a customer-facing defect, preparing usable engineering evidence, and proving the fix worked.</p><div className="fit-event"><strong>The must-win event</strong><span>A complaint spike after a release affects several strategic accounts, but every team sees only part of the evidence.</span></div></div><div className="fit-grid"><article><span>Best fit now</span><ul><li><Check aria-hidden="true" size={15}/> 50–300 employee B2B SaaS</li><li><Check aria-hidden="true" size={15}/> Intercom or Zendesk plus GitHub</li><li><Check aria-hidden="true" size={15}/> Linear or Jira and multiple repositories</li><li><Check aria-hidden="true" size={15}/> 1,000+ support conversations each month</li><li><Check aria-hidden="true" size={15}/> Enterprise accounts, renewals, or SLAs at risk</li></ul></article><article className="fit-later"><span>Not the first use case</span><ul><li>Public voting and idea boards</li><li>General research repositories</li><li>Roadmap planning suites</li><li>Consumer review analytics</li><li>Autonomous production code changes</li></ul></article></div></section>

    <section className="workflow-section" id="workflow"><div className="section-intro"><span>Signal → resolution</span><h2>One continuous, governed workflow.</h2><p>Every recommendation stays connected to the evidence that produced it.</p></div><div className="workflow-track">{workflow.map((item,index) => <div className="workflow-step" key={item}><span>{index+1}</span><strong>{item}</strong></div>)}</div><div className="workflow-summary"><article><TimerReset size={22}/><div><strong>Detect earlier</strong><p>Surface emerging clusters, release-linked complaint spikes, and high-value customer incidents.</p></div></article><article><Users size={22}/><div><strong>Decide together</strong><p>Give product, engineering, support, and success teams the same customer and technical evidence.</p></div></article><article><BadgeCheck size={22}/><div><strong>Prove the outcome</strong><p>Verify deployment, draft customer follow-ups, and measure whether complaints actually declined.</p></div></article></div></section>

    <section className="trust-section" id="trust"><div><span className="section-label">Trust by design</span><h2>AI recommendations you can inspect—and refuse.</h2><p>Customer content is evidence, never agent instruction. Confidence, assumptions, affected systems, shared data, and reversibility remain visible before every meaningful action.</p><ul><li><Check aria-hidden="true" size={15}/> Configurable human approval gates</li><li><Check aria-hidden="true" size={15}/> PII detection and redaction</li><li><Check aria-hidden="true" size={15}/> Tenant-scoped records and audit events</li><li><Check aria-hidden="true" size={15}/> Idempotent, rate-limited action APIs</li></ul></div><div className="trust-card"><div className="trust-card-head"><ShieldCheck aria-hidden="true" size={20}/><div><strong>Proposed action</strong><small>Create GitHub issue in analytics-api</small></div><span>Low risk</span></div><dl><div><dt>Reason</dt><dd>3 corroborating reports affecting $394k ARR</dd></div><div><dt>Confidence</dt><dd>68% · hypothesis, not confirmed cause</dd></div><div><dt>Data shared</dt><dd>Redacted quotes and environment metadata</dd></div><div><dt>Reversible</dt><dd>Yes · issue can be edited or closed</dd></div></dl><div className="trust-card-actions"><button type="button" disabled>Reject</button><button type="button" disabled>Approve simulated action</button></div></div></section>

    <section className="pricing-section" id="pricing"><div className="section-intro"><span>Early-access pricing</span><h2>Free to evaluate. Paid when it owns a real workflow.</h2><p>This is a B2B operational product, not a free production developer tool. Start with the risk-free sandbox, then prove accuracy and ROI in one tightly scoped paid pilot.</p></div><div className="pricing-grid">{launchPlans.map((plan) => <article className={plan.featured ? "featured" : ""} key={plan.id}>{plan.featured && <span className="pricing-flag">Recommended</span>}<div className="pricing-name">{plan.name}</div><div className="pricing-price">{plan.price}</div><div className="pricing-cadence">{plan.cadence}</div><p>{plan.description}</p><ul>{plan.features.map((feature) => <li key={feature}><Check aria-hidden="true" size={14}/>{feature}</li>)}</ul>{plan.href.startsWith("/") ? <Link className={`btn ${plan.featured ? "primary" : ""}`} href={plan.href}>{plan.callToAction}</Link> : <a className={`btn ${plan.featured ? "primary" : ""}`} href={plan.href}>{plan.callToAction}</a>}</article>)}</div><p className="pricing-note">{launchPricingNote} Usage caps stop processing instead of triggering surprise upgrades.</p></section>

    <section className="landing-cta"><div><span>Start with evidence</span><h2>See one customer defect move from support signal to verified resolution.</h2><p>The free sandbox uses clearly labeled simulated data. Design-partner applications do not connect a live system until production security gates are complete.</p></div><div className="landing-cta-actions"><Link className="btn primary large" href="/overview">Explore the sandbox <ArrowRight aria-hidden="true" size={16}/></Link><a className="btn large" href="mailto:shanmukhsain@gmail.com?subject=Feedback-to-Fix%20Design%20Partner%20Pilot">Apply for pilot</a></div></section>
    </main>

    <footer className="landing-footer"><Link className="landing-brand" href="/"><span className="brandmark" aria-hidden="true">F</span><strong>Feelow AI</strong></Link><p>Customer-reported problem to verified fix.</p><div><Link href="/overview">Free sandbox</Link><a href="#pricing">Pricing</a><a href="#trust">Security</a><a href="mailto:shanmukhsain@gmail.com">Contact</a></div></footer>
  </div>;
}
